services:

  database:
    image: postgres
    container_name: database
    networks:
      - compose-bridge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dados
    ports:
      - "5432:5432"

  backend:
    image: espacol_backend:1.0
    container_name: backend
    depends_on:
      - database
    networks:
      - compose-bridge
    ports:
      - "8080:8080"

networks:
  compose-bridge:
    driver: bridge
