services:

  database:
    image: postgres
    container_name: database
    networks:
      - compose-bridge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dados_espaco_l
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    networks:
      - compose-bridge
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://database:5432/dados_espaco_l
    ports:
      - "8080:8080"

networks:
  compose-bridge:
    driver: bridge
